import type { NextPage } from "next";
import Head from "next/head";
import { motion } from "framer-motion";
import { AppearX } from "animations";

const Product: NextPage = () => {
	return (
		<>
			<Head>
				<title>Framer Motion Practice</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<motion.section
				initial={{
					opacity: 0,
					x: "50%",
				}}
				animate={{
					opacity: 1,
					x: 0,
					transition: {
						duration: 0.5,
						type: "tween",
						when: "beforeChildren",
						ease: [1.0, 0.0, 0.685, 0.46],
					},
				}}
				className={`
			w-full h-screen max-h-screen 
			flex flex-col gap-4 pt-8 bg-[#aaa6d6] overflow-hidden`}
			>
				<div className="w-full h-[40%]"></div>
				<motion.div
					initial={{ opacity: 0, y: "100%" }}
					animate={{
						opacity: 1,
						y: "0",
						transition: {
							duration: 0.4,
							type: "tween",
							ease: "easeInOut",
							delay: 1,
						},
					}}
					className="bg-[#f4f5fc] rounded-t-3xl h-[60%] w-full"
				></motion.div>
			</motion.section>
		</>
	);
};

export default Product;
