import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Framer Motion Practice</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<section className="sm:hidden w-full h-screen flex flex-col gap-4 pt-8 bg-[#f4f5fc]"></section>

			{/* FOR BIGGER SCREENS */}
			<section className="hidden sm:flex justify-center items-center text-2xl w-full min-h-screen p-6 text-center font-medium">
				This website is only made for mobile phones, resize your window to a
				smaller screen or open website in a phone
			</section>
		</>
	);
};

export default Home;
