import type { NextPage } from "next";
import Head from "next/head";
import Header from "@/components/Header";
import FilterTab from "@/components/FilterTab";
import Products from "@/components/Products";

interface Props {}

const Home: NextPage<Props> = ({}) => {
	return (
		<>
			<Head>
				<title>Framer Motion Practice</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<section className="max-w-screen-xl mx-auto w-full h-screen flex flex-col gap-4 pt-8 bg-[#f4f5fc]">
				<Header />
				<FilterTab />
				<Products />
			</section>
		</>
	);
};
export default Home;
