import { useContext } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { StoreContext } from "pages/_app";

import Header from "components/Header";
import FilterTab from "components/FilterTab";
import Products from "components/Products";
import CartMiniView from "components/CartMiniView";
import { AnimatePresence, motion } from "framer-motion";

interface Props {}

const Home: NextPage<Props> = ({}) => {
	const { cart } = useContext(StoreContext);

	return (
		<>
			<Head>
				<title>Framer Motion Practice</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<motion.section
				initial={{ opacity: 1 }}
				animate={{ opacity: 1 }}
				exit={{ opacity: 0 }}
				className={`
			w-full max-h-screen 
			flex flex-col gap-4 pt-8 bg-[#f4f5fc] lg:hidden`}
			>
				<Header />
				<FilterTab />
				<Products />
			</motion.section>
			{cart.length ? <CartMiniView /> : null}
			<section className="hidden lg:flex justify-center items-center p-8 text-3xl h-screen">
				This website doesnt designed for big screens, try in a small screen
				(hint: below than 1024px)
			</section>
		</>
	);
};
export default Home;
